### PR TITLE
Add Jenkinsfile to run the build

### PR DESCRIPTION
**Pull request by ColMelvin**

### CODE REVIEW

**Comment by ColMelvin** [comment]
Thanks!  I had a feeling something was wrong when I couldn't see the project on ci.jenkins.io.

**Comment by ColMelvin** [comment]
Oh, of course, PRs with changes to the Jenkinsfile are a security risk.  That explains why it isn't running.

In that case, how do I go about testing something like this?  Or do I test it?

**Comment by oleg-nenashev** [comment]
> You will also need to create an INFRA ticket to enable CI for a non-plugin repository

It's not a big deal. E.g. you can just clone/adjust https://issues.jenkins-ci.org/browse/INFRA-1521

**Comment by ColMelvin** [comment]
Changes made and case opened: https://issues.jenkins-ci.org/browse/INFRA-1562

**Comment by ColMelvin** [comment]
@oleg-nenashev  Per INFRA-1562: Once this pull request merges, CI should begin.

**Comment by oleg-nenashev** [comment]
```
The specified user settings file does not exist: /home/jenkins/workspace/braries_xtrigger-lib_master-OJ3FPXB45DEHILHACI6Z7ILXH6YYZIN44XP7NPTKCYRFSWZZWNHQ/settings-azure.xml
```

Azure profile has been added without a proper settings file wrapper. 
I will remove it for now and then create a library step

**Pull request merged**
